// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MostafaGamal/sdk/models/components"
)

type CreateAisConnectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Connection created successfully
	NewAisConnectionResponse *components.NewAisConnectionResponse
}

func (o *CreateAisConnectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateAisConnectionResponse) GetNewAisConnectionResponse() *components.NewAisConnectionResponse {
	if o == nil {
		return nil
	}
	return o.NewAisConnectionResponse
}
