// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MostafaGamal/sdk/models/components"
)

type DeleteAisConnectionRequest struct {
	// The `id` of the connection for which will be deleted.
	ConnectionID int64 `pathParam:"style=simple,explode=false,name=connection_id"`
}

func (o *DeleteAisConnectionRequest) GetConnectionID() int64 {
	if o == nil {
		return 0
	}
	return o.ConnectionID
}

type DeleteAisConnectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteAisConnectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
