// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MostafaGamal/sdk/internal/utils"
	"github.com/MostafaGamal/sdk/models/components"
)

type GetAccountTransactionsRequest struct {
	Limit        *int64  `default:"10" queryParam:"style=form,explode=true,name=limit"`
	Offset       *string `queryParam:"style=form,explode=true,name=offset"`
	ConnectionID int64   `pathParam:"style=simple,explode=false,name=connection_id"`
	// The `id` of the account for which to retrieve the account balance information.
	AccountID int64 `pathParam:"style=simple,explode=false,name=account_id"`
}

func (g GetAccountTransactionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAccountTransactionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetAccountTransactionsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetAccountTransactionsRequest) GetOffset() *string {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *GetAccountTransactionsRequest) GetConnectionID() int64 {
	if o == nil {
		return 0
	}
	return o.ConnectionID
}

func (o *GetAccountTransactionsRequest) GetAccountID() int64 {
	if o == nil {
		return 0
	}
	return o.AccountID
}

type GetAccountTransactionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	TransactionsResponse *components.TransactionsResponse
}

func (o *GetAccountTransactionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAccountTransactionsResponse) GetTransactionsResponse() *components.TransactionsResponse {
	if o == nil {
		return nil
	}
	return o.TransactionsResponse
}
