// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MostafaGamal/sdk/models/components"
)

type GetKycStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// KYB status retrieved successfully
	KYCStatus *components.KYCStatus
}

func (o *GetKycStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetKycStatusResponse) GetKYCStatus() *components.KYCStatus {
	if o == nil {
		return nil
	}
	return o.KYCStatus
}
