// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MostafaGamal/sdk/internal/utils"
	"github.com/MostafaGamal/sdk/models/components"
)

type GetTransactionsRequest struct {
	Limit  *int64  `default:"10" queryParam:"style=form,explode=true,name=limit"`
	Offset *string `queryParam:"style=form,explode=true,name=offset"`
}

func (g GetTransactionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTransactionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetTransactionsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetTransactionsRequest) GetOffset() *string {
	if o == nil {
		return nil
	}
	return o.Offset
}

type GetTransactionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	TransactionsResponse *components.TransactionsResponse
}

func (o *GetTransactionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTransactionsResponse) GetTransactionsResponse() *components.TransactionsResponse {
	if o == nil {
		return nil
	}
	return o.TransactionsResponse
}
