// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MostafaGamal/sdk/models/components"
)

type GetUserAccountsRequest struct {
	ConnectionID int64 `pathParam:"style=simple,explode=false,name=connection_id"`
}

func (o *GetUserAccountsRequest) GetConnectionID() int64 {
	if o == nil {
		return 0
	}
	return o.ConnectionID
}

type GetUserAccountsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AccountsResponse *components.AccountsResponse
}

func (o *GetUserAccountsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetUserAccountsResponse) GetAccountsResponse() *components.AccountsResponse {
	if o == nil {
		return nil
	}
	return o.AccountsResponse
}
