// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MostafaGamal/sdk/internal/utils"
	"github.com/MostafaGamal/sdk/models/components"
)

type GetUserAccountBalancesRequest struct {
	Limit  *int64  `default:"10" queryParam:"style=form,explode=true,name=limit"`
	Offset *string `queryParam:"style=form,explode=true,name=offset"`
	// Key to Sort by followed by order (- for descending)
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// Filter by resources having fields starting with this parameter value
	Filter       *string `queryParam:"style=form,explode=true,name=filter"`
	ConnectionID int64   `pathParam:"style=simple,explode=false,name=connection_id"`
	// The `id` of the account for which to retrieve the account balance information.
	AccountID int64 `pathParam:"style=simple,explode=false,name=account_id"`
}

func (g GetUserAccountBalancesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUserAccountBalancesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetUserAccountBalancesRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetUserAccountBalancesRequest) GetOffset() *string {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *GetUserAccountBalancesRequest) GetSort() *string {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *GetUserAccountBalancesRequest) GetFilter() *string {
	if o == nil {
		return nil
	}
	return o.Filter
}

func (o *GetUserAccountBalancesRequest) GetConnectionID() int64 {
	if o == nil {
		return 0
	}
	return o.ConnectionID
}

func (o *GetUserAccountBalancesRequest) GetAccountID() int64 {
	if o == nil {
		return 0
	}
	return o.AccountID
}

type GetUserAccountBalancesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AccountBalancesResponse *components.AccountBalancesResponse
}

func (o *GetUserAccountBalancesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetUserAccountBalancesResponse) GetAccountBalancesResponse() *components.AccountBalancesResponse {
	if o == nil {
		return nil
	}
	return o.AccountBalancesResponse
}
