// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MostafaGamal/sdk/models/components"
)

type GetUserAccountByIDRequest struct {
	// The `id` of the account for which to retrieve the account balance information.
	AccountID    int64 `pathParam:"style=simple,explode=false,name=account_id"`
	ConnectionID int64 `pathParam:"style=simple,explode=false,name=connection_id"`
}

func (o *GetUserAccountByIDRequest) GetAccountID() int64 {
	if o == nil {
		return 0
	}
	return o.AccountID
}

func (o *GetUserAccountByIDRequest) GetConnectionID() int64 {
	if o == nil {
		return 0
	}
	return o.ConnectionID
}

type GetUserAccountByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Account details retrieved successfully
	Account *components.Account
}

func (o *GetUserAccountByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetUserAccountByIDResponse) GetAccount() *components.Account {
	if o == nil {
		return nil
	}
	return o.Account
}
