// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MostafaGamal/sdk/models/components"
)

type GetUserInfoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Current user short details.
	UserDetails *components.UserDetails
}

func (o *GetUserInfoResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetUserInfoResponse) GetUserDetails() *components.UserDetails {
	if o == nil {
		return nil
	}
	return o.UserDetails
}
