// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// Error - Unauthorized access to the resource.
type Error struct {
	// Unique identifier for the error
	ID string `json:"id"`
	// Error code is to identify the type of error.
	Code int64 `json:"code"`
	// Friendly error message to show to the user
	Message string `json:"message"`
	// Detailed technical error description used by system admins and developers
	Detail *string `json:"detail,omitempty"`
}

var _ error = &Error{}

func (e *Error) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
