// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// Validation - Request didn't pass validation.
type Validation struct {
	// Unique identifier for the error
	ID string `json:"id"`
	// Error code is to identify the type of error.
	Code int64 `json:"code"`
	// Friendly error message to show to the user
	Message string `json:"message"`
	// Detailed technical error description used by system admins and developers
	Detail *string `json:"detail,omitempty"`
	// Validation errors
	Errors map[string][]string `json:"errors"`
}

var _ error = &Validation{}

func (e *Validation) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
