// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AccountBalancesResponse - OK
type AccountBalancesResponse struct {
	Data []AccountBalance `json:"data,omitempty"`
	// The maximum number of items that can be returned per page.
	PerPage *int64 `json:"per_page,omitempty"`
	// Could be used to retrieve the next page.
	NextCursor *string `json:"next_cursor,omitempty"`
	// Could be used to retrieve the previous page.
	PrevCursor *string `json:"prev_cursor,omitempty"`
}

func (o *AccountBalancesResponse) GetData() []AccountBalance {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *AccountBalancesResponse) GetPerPage() *int64 {
	if o == nil {
		return nil
	}
	return o.PerPage
}

func (o *AccountBalancesResponse) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *AccountBalancesResponse) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}
