// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AccountsResponse - OK
type AccountsResponse struct {
	Data []Account `json:"data,omitempty"`
	// The maximum number of items that can be returned per page.
	PerPage *int64 `json:"per_page,omitempty"`
	// Could be used to retrieve the next page.
	NextCursor *string `json:"next_cursor,omitempty"`
	// Could be used to retrieve the previous page.
	PrevCursor *string `json:"prev_cursor,omitempty"`
}

func (o *AccountsResponse) GetData() []Account {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *AccountsResponse) GetPerPage() *int64 {
	if o == nil {
		return nil
	}
	return o.PerPage
}

func (o *AccountsResponse) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *AccountsResponse) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}
