// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AisConnectionsResponse - List of the user's created connections (accounts)
type AisConnectionsResponse struct {
	Data []AisConnections `json:"data,omitempty"`
	// The maximum number of items that can be returned per page.
	PerPage *int64 `json:"per_page,omitempty"`
	// Could be used to retrieve the next page.
	NextCursor *string `json:"next_cursor,omitempty"`
	// Could be used to retrieve the previous page.
	PrevCursor *string `json:"prev_cursor,omitempty"`
}

func (o *AisConnectionsResponse) GetData() []AisConnections {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *AisConnectionsResponse) GetPerPage() *int64 {
	if o == nil {
		return nil
	}
	return o.PerPage
}

func (o *AisConnectionsResponse) GetNextCursor() *string {
	if o == nil {
		return nil
	}
	return o.NextCursor
}

func (o *AisConnectionsResponse) GetPrevCursor() *string {
	if o == nil {
		return nil
	}
	return o.PrevCursor
}
