// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type BusinessType string

const (
	BusinessTypeSoleProprietorship BusinessType = "sole_proprietorship"
	BusinessTypePartnership        BusinessType = "partnership"
	BusinessTypeCorporation        BusinessType = "corporation"
	BusinessTypeLlc                BusinessType = "llc"
)

func (e BusinessType) ToPointer() *BusinessType {
	return &e
}
func (e *BusinessType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sole_proprietorship":
		fallthrough
	case "partnership":
		fallthrough
	case "corporation":
		fallthrough
	case "llc":
		*e = BusinessType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BusinessType: %v", v)
	}
}

type ContactPerson struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

func (o *ContactPerson) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ContactPerson) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *ContactPerson) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}

type KYCRequest struct {
	BusinessName               *string        `json:"businessName,omitempty"`
	BusinessAddress            *string        `json:"businessAddress,omitempty"`
	BusinessRegistrationNumber *string        `json:"businessRegistrationNumber,omitempty"`
	BusinessType               *BusinessType  `json:"businessType,omitempty"`
	ContactPerson              *ContactPerson `json:"contactPerson,omitempty"`
}

func (o *KYCRequest) GetBusinessName() *string {
	if o == nil {
		return nil
	}
	return o.BusinessName
}

func (o *KYCRequest) GetBusinessAddress() *string {
	if o == nil {
		return nil
	}
	return o.BusinessAddress
}

func (o *KYCRequest) GetBusinessRegistrationNumber() *string {
	if o == nil {
		return nil
	}
	return o.BusinessRegistrationNumber
}

func (o *KYCRequest) GetBusinessType() *BusinessType {
	if o == nil {
		return nil
	}
	return o.BusinessType
}

func (o *KYCRequest) GetContactPerson() *ContactPerson {
	if o == nil {
		return nil
	}
	return o.ContactPerson
}
