// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MostafaGamal/sdk/internal/utils"
	"time"
)

// NewAisConnectionResponse - Connection created successfully
type NewAisConnectionResponse struct {
	// `auth_session_url` to be used to access FINX Connect Widget for connection creation.
	AuthSessionURL *string `json:"auth_session_url,omitempty"`
	// The date and time when `auth_session_url` expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

func (n NewAisConnectionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NewAisConnectionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *NewAisConnectionResponse) GetAuthSessionURL() *string {
	if o == nil {
		return nil
	}
	return o.AuthSessionURL
}

func (o *NewAisConnectionResponse) GetExpiresAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ExpiresAt
}
