// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	OpenID *string `security:"scheme,type=openIdConnect,name=Authorization,env=pfm_open_id"`
}

func (o *Security) GetOpenID() *string {
	if o == nil {
		return nil
	}
	return o.OpenID
}
