// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UserDetails - Current user short details.
type UserDetails struct {
	ID      int64  `json:"id"`
	Email   string `json:"email"`
	Name    string `json:"name"`
	IsAdmin bool   `json:"is_admin"`
}

func (o *UserDetails) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *UserDetails) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *UserDetails) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UserDetails) GetIsAdmin() bool {
	if o == nil {
		return false
	}
	return o.IsAdmin
}
