workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    sdk -OAS:
        inputs:
            - location: https://raw.githubusercontent.com/MostafaGamal/sdk/refs/heads/master/pfm-apis.yaml
        output: '  '
        registry:
            location: registry.speakeasyapi.dev/fintech-galaxy/fintech-galaxy/pfm--oas
targets:
    sdk:
        target: go
        source: sdk -OAS
